<?php

DEFINE('PERFIL_ADMINISTRADOR',1);
//DEFINE('PERFIL_TECNICO_ADMIN',2);
DEFINE('PERFIL_TECNICO',2);
DEFINE('PERFIL_BASICO',3);

DEFINE('EQUIPO',1);
DEFINE('PRESTACION',2);

DEFINE('ESTADO_ALTA',1);
DEFINE('ESTADO_BAJA',9);

define("BASIC_PASSWORD",1234);

define("ESTADO_ORDEN_DISPONIBLE",0);
define("ESTADO_ORDEN_PENDIENTE",1);
define("ESTADO_ORDEN_ENCURSO",2);
define("ESTADO_ORDEN_RESUELTA",3);
define("ESTADO_ORDEN_FINALIZADA",4);
define("ESTADO_ORDEN_CANCELADA",5);
define("ESTADO_ORDEN_RECHAZADA",6);


define("ENTIDAD_INTERNA",1);
define("ENTIDAD_PRESTADOR_SERVICIO",2);
define("ENTIDAD_PROVEEDOR",3);